name: tickt
description: "A Flutter application for event ticket management"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.1.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  image_picker: ^1.0.7
  qr_flutter: 4.1.0
  mobile_scanner: ^3.5.6
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  audioplayers: ^5.2.1
  fl_chart: ^0.66.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.5.3
  mask_text_input_formatter: ^2.9.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/bip.mp3
    - assets/images/
    - assets/icons/
    - .env
    - assets/lottie/confetti.json